version: '3'
services:
    vue:
      build:
         context: vue
      environment:
          TZ: Asia/Tokyo
      tty: true
      volumes:
          - ./vue/navigation-map/:/usr/src/app
      ports:
           - 28080:8080