version: '3'
services:
    vue:
      build: .
      environment:
          TZ: Asia/Tokyo
      tty: true
      volumes:
          - ./navigation-map/:/usr/src/app
      ports:
           - 28080:8080